= 3D face image toolbox overview

== Overview
As described in <<2DFaceOverview>>, if the TOE implements 3D based face verification, the evaluator doesn’t need to create 2D face artefacts defined in <<2DFaceOverview>>, however, the evaluator shall create and test 3D face artefacts defined in this toolbox that try to mimic three-dimensional geometry of a real face. If the TOE doesn’t implement 3D based face verification or the evaluator can’t confirm about it, the evaluator shall create and test both 2D and 3D artefacts defined in <<2DFaceOverview>> and this toolbox.

== Face presentation attack

There are three categories of 3D face artefacts or masks studied in existing research papers. Some papers report successful presentation attacks using target user’s face with some artefacts (e.g. putting special glasses above the sleeping target user’s face to bypass the attention detection mechanism) however, this toolbox doesn’t consider such attack scenarios because attack potential required to exploit these scenarios is clearly beyond the Basic attack potential.

- Printed Face mask
+
Printed photo is bent and worn as a face mask to create the illusion of 3D in a real face.

- 3D face mask from 2D face image
+
Predict the 3D features of the face from a single 2D image or photo and create 3D face masks from the predicted 3D face image.
- 3D face mask from 3D face image
+
Get a 3D face image through a 3D scan of the face or using molding material and create 3D face masks from the actual 3D image of a target user’s face.

The last category, 3D face mask from 3D face image, is also out of scope of this toolbox because it’s beyond the scope of Basic attack potential. As described in <<BIOSD>>, the attack potential shall be rated as follows.

-	*Elapsed time* for *Identification*
+
*⇐ one week* (1)

-	*Window of Opportunity (Access to TOE)* for *Exploitation*
+
*Moderate* (4)

In addition to them, following factors for creating a 3D face mask from 3D face image should be rated as follows.

-	*Window of Opportunity (Access to Biometric Characteristics)*
+
*Moderate* (4), because 3D scan of the face or using molding material requires direct contact with a target user

-	*Expertise* for *Identification*
+
*Proficient* (2), because using a 3D scanner and 3D printer or using molding material and resin for creating sufficient quality of 3D face masks requires some level of knowledge and experiences that the Layman doesn’t has.

In total, the attack potential for 3D face mask from 3D face image is at least 11, that is beyond the Basic attack potential (10). 
This is the reason why this toolbox excludes this type of artefacts. However, both Printed Face mask and 3D face mask from 2D face image 
is within the scope of the Basic attack potential because only 2D image of target face is required to create both face artefact, 
because *Window of Opportunity (Access to Biometric Characteristics)* should be rated as *Immediate* (0).

3D face presentation attack can be conducted through the following process using 3D face masks described above.

. Capture face images of a target user using a camera

. Print captured image on a paper for Printed Face mask, or convert the captured 2D image to 3D image and create a face mask for 3D face mask from 2D face image

. Wear a face mask and present it to the TOE

== Face presentation attack detection
The 3D face mask contains the quality defect that results in the appearance difference from a genuine face. For example, the skin 
texture and detailed facial structures in masks have perceivable differences compared to those in real faces. The 3D face mask also lacks the facial motion such as facial expression changes, eye blinks and mouth movements because it is made of hard materials. Several PAD methods that utilize such cues have been studied and reported by researchers. Other PAD methods utilize liveness cues such as thermal signatures, gaze information, pulse or heartbeat signals to detect 3D face masks. However, normally such design information of the PAD is not available to the evaluator and he or she needs to test the TOE in black box manner.

== Common test protocol
Test protocol is quite similar as one defined in <<2DFaceOverview>>. This section only shows the differences between the two.

=== Presentation attack with Printed Face mask
This attack is almost same as the printed photo attack except the evaluator shall bend and wear the printed paper as a face mask instead of presenting it to the TOE by hand. So, the method of presentation is the only difference.

[start=4]
. Artefact presentation
+
.. The evaluator shall bend and wear a Printed Face mask using tape or paste and present it to the TOE under the same controlled environment.
+
.. The evaluator shall present a Printed Face mask in a way to minimize the reflection from ambient lighting.

=== Presentation attack with 3D face mask from 2D face image
This evaluator shall create and wear a 3D face mask. So, the method of creation and presentation are different from ones in <<2DFaceOverview>>.

[start=3]
. Artefact creation
+
.. The evaluator shall generate a 3D face image from a captured 2D face images using software tools. 
+
.. The evaluator shall create a 3D face mask from the image using 3D printer. Size of face mask shall be same as the test user’s face.
+
.. The evaluator shall use those tools that meet requirements defined in <<3DFaceInventory>> to create artefacts.

. Artefact presentation
+
.. The evaluator shall wear a 3D face mask and present it to the TOE under the same controlled environment.
+
+ 
.. The evaluator shall present a 3D face mask in a way to minimize the reflection from ambient lighting.

== Requirement for tools
Requirement for tools for Printed Face mask is same as ones defined for printed photo attack in <<2DFaceInventory>>. The evaluator shall 
create normal and high quality printed photo and wear it instead of presenting it by hand.

Creation of a 3D face mask from 2D face image requires different type of tools. Number of such tools is limited so <<3DFaceInventory>> defines just one type of tools. 

== Test items
The evaluator shall create artefacts defined in all test items listed in <<3DFaceList>>. <<ToolOverview>> defines required number of attempts for the independent testing and maximum timeframe for both independent and penetration testing.

== Pass/fail criteria
If Pass/fail criteria is defined in the test items the evaluator shall follow them, otherwise follow criteria defined in <<BIOSD>> and <<ToolOverview>>.

== Useful information 
3D Face Image Toolbox was created based on research papers listed in <<3DFaceREF>>. The evaluator should read them before conducting the PAD testing because they include more detailed information about PAD test methods.

=== Related Documents
[bibliography]
- [#BIOSD]#[BIOSD]# Supporting Document Mandatory Technical Document: Evaluation Activities for collaborative PP-Module for Biometric enrolment and verification - for unlocking the device -, December 20, 2019, Version 0.92 - [BIOSD].
- [#ToolOverview]#[ToolOverview]# Toolbox Overview, TBD.
- [#2DFaceOverview]#[2DFaceOverview]# 2D Face Image Toolbox Overview, TBD.
- [#2DFaceInventory]#[2DFaceInventory]# 2D Face Image Toolbox Inventory, TBD.
- [#2DFaceList]#[2DFaceList]# 2D Face Image Verification List, TBD.
- [#2DFaceREF]#[2DFaceREF]# 2D Face Image References, TBD.
- [#3DFaceOverview]#[3DFaceOverview]# This document
- [#3DFaceInventory]#[3DFaceInventory]# 3D Face Image Toolbox Inventory, TBD.
- [#3DFaceList]#[3DFaceList]# 3D Face Image Verification List, TBD.
- [#3DFaceREF]#[3DFaceREF]# 3D Face Image References, TBD.
