 
= Toolbox Overview for Testing Compliance for Mobile Biometric Enrolment and Verification 
:showtitle:
:toc:
:sectnums:
:imagesdir: images
:revnumber: 0.3
:revdate: 2019-05-03

== Introduction
This document an its child documents contains a toolbox of Presentation Attack Species (PAS) for various biometric modalities. This toolbox shall be used to test the PAD functionality of a TOE during an evaluation in compliance to <<PP>>.

This toolbox document shall be used to test for the implementation of the SFR FIA_MBV_EXT.3 from <<PP>>. It contains content for the following biometric modalities:

* Eye
* Face
** 2D Image
** 3D Image
* Fingerprint
* Vein

This document presents, at a high level, the expected methodology of the PAD functionality tests for all modalities, including preparation, test subjects and the pass/fail criteria.

=== Independent vs Vulnerability Testing

It should be noted that the toolbox as contained in this document focuses on a functional approach of testing as required by the assurance component ATE_IND.1. Each toolbox contains the state of the art of the Presentation Attack Instruments of its respective modality. A TOE compliant to the <<PP>> is expected to reliably recognize these PAI. The functional approach of the toolboxes is however not suitable for any test in the context of AVA_VAN. 

== Overall Test Approach
As it can not be assumed that every TOE will return a dedicated result for the PAD functionality, success for an presentation attack is defined for the whole biometric functionality, including the matcher. This means that - in order to successfully overcome the TOE by the use of an artefact - a genuine person (the tester) has to be enrolled into the TOE, an artefact has to be created for the corresponding biometric modality of the tester and the artefact has to produce a match (i.e. a successful verification).

=== Preparation
Before the actual test can start, the following pre-requisites need to be met:

* It has to be ensured that the subject whose biometric data is used to produce the artefacts for testing is enrolled into the TOE. 
** Successful enrollment needs to be documented and verified by performing at least 5 genuine transactions with the TOE. No errors shall occur during the 5 genuine transactions. 
** If any errors occur, the enrollment process shall be repeated. In case of repeated errors, it should be considered to use a different biometric characteristic (this could mean to use a different finger of a subject or even use a different subject).

Each toolbox will provide an inventory of tools needed to perform the tests. These tools must be available to complete the testing process. The tools are described and not picked. For example, a class of printer or camera is specified, but not a specific printer or camera model.

=== PAI Production 
The production of the PAI for each toolbox shall be performed as follows:

* The tester shall produce three (3) of each PAI as defined by the toolbox documents. 
* The production of each PAI shall be documented in a manner that the production can be reproduced. 
* Each produced artefact shall be identified by a unique identifier. This identifier shall be be attached to the artefact at all times (as far as this is possible without destroying the artefact)

=== Testing
The actual test of each PAI shall be conducted as follows:

* The artefact shall be applied to the TOE 10 times
** If the TOE matches the previously enrolled user by the use of the artefact, the attempt is considered a fail 
** If the TOE rejects the attempt, this is considered being a pass

=== Pass/Fail Criteria
The following pass criteria shall be applied if no other criteria are defined in the individual modality toolbox documents. 

A TOE passes the test if and only if it reliably defeats the use of *all artefacts* that have to be built according to the toolbox. This means that none of the artefacts must be able to reproducibly overcome the TOE. 

To reproducibly overcome the TOE by the use of a *certain artefact* in the outlined test scenario is defined as follows:

* If a certain PAI does not match in any of its 10 attempts, the TOE passes this PAI. 
* If a certain PAI matches 1 time out of 10, the TOE passes this PAI. 
* If a certain PAI matches 2 times out of 10, an additional 10 attempts shall be added to the test
* If a certain PAI matches 3 times or more (either of the 10 attempts or of the extended set of 20 attempts), the TOE fails that PAI



= Literature

- [[[PP]]] collaborative Protection Profile Module for Mobile biometric enrolment and verification - for unlocking the device 

