= Toolbox Overview 
:showtitle:
:toc:
:sectnums:
:imagesdir: images
:icons: font
:revnumber: 0.5
:revdate: 2019-12-06

== Introduction
The TOE may be vulnerable to presentation attacks where attackers attempt to subvert the biometric enrolment or verification by presenting the Presentation Attack Instrument(PAI)s that are natural biometric characteristics such as dead eye or artefacts holding copied or faked characteristics. Using national biometric characteristics is out of scope of <<BIOPP-Module>> evaluation and the evaluator shall create only artefacts to evaluate the TOE. 

Toolbox defines the common artefacts for each biometric modality based on publicly available information (e.g. research papers), experiences and knowledge shared among the BIO-iTC members. The evaluator needs to read <<SD>> Section 6 first to use a toolbox because it explains how the evaluator shall use it during ATE_IND.1 (Independent test) and AVA_VAN.1 (Penetration test) evaluation for PAD in detail.

This overview is originally developped for evaluation activities for FIA_MBV_EXT.3, however, the evaluator can apply the same principle to evaluation activities for FIA_MBE_EXT.3.

== Biometric modalities supported

Currently toolbox is developed for the following biometric modalities:

* Eye
* Face
** 2D Image
** 3D Image
* Fingerprint
* Vein

== Purpose of this toolbox overview

This toolbox overview describes anything in common for all toolboxes, rather than repeating the same information in each toolbox. The evalator shall refer both the toolbox overview and relevant toolbox to perform independent and penetration test. If there is conflict between the toolbox overview and each toolbox, the toolbox takes precedence over the toolbox overvew.

== Structure of toolbox

Each toolbox share the same structure and includes following sections.

* _modality name_ Toolbox overview  
+
This section provides specific information only applicable to relevant biometric modality.

* _modality name_ Toolbox Inventory
+
This section categorizes tools and materials that the evaluator shall use to capture a image of biometric characteristics and produce artefacts.

* Mobile Toolbox for _modality name_ Verification List  
+
This section summarizes all test items that the evaluator shall peform during independent test. As explained in <<SD>> Section 6, the evaluator shall select specific test items for penetration test based on the result of independent test. 

* References
+
This section lists all publicly available information referred to create a toolbox.

* Test items
+
Each test item includes the following sub-sections. This toolbox overview provide a general test protocol in common for all toolboxes and these test items describe more detailed information to enable repeatable testing.
+
|===

|Sub-section name | Description

|Number
|Identification number of test

|Attack type
|Category of attack

|Overview
|General overview of test

|Input
|Required input to produce artefacts

|Tools
|Required tools to capture a image of biometric characteristics and produce artefacts

|Recipe
|Procedure to create artefacts

|Variations
|Variations of tests that the evaluator should consider AVA_VAN.1 evaluation

|Prerequisite
|Any conditions that should meet to perform each test

|Presentation
|Detail instraction to present artefact to the TOE

|Attack Potential
|Attack potential rating that the evaluator shall use for AVA_VAN.1 evaluation

|Pass Criteria
|If this Pass criteria is defined in test items, evaluator shall follow it. Otherwise, the evaluator shall follow criteria defined in this toolbox overview for independent test and one defined in <<SD>> Section 9.3 for penetration test  

|===

== Common guidance for independent test
As explained in <<BIOPP-Module>>, the TOE is the whole biometric system, including Comparison, Decision and Presentation Attack Detection Subsystems. This means that - in order to successfully overcome the TOE by the use of artefacts - a genuine person (test subject) has to be enrolled into the TOE, artefacts have to be created referring the toolbox for the corresponding biometric modality and artefacts have to produce a attack presentation match (i.e. a successful presentation attack).

The following guidance is common in all toolboxes. More specific guidance to specific biometric modality is provided in each toolbox. 

=== General test protocol
Presentation attack can be performed through the following three steps. 

==== Preparation
Before the actual test can start, the following pre-requisites need to be met:

* It has to be ensured that the test subject whose body part is used to produce the artefacts for testing is enrolled into the TOE correctly as follows.

** Enrolment shall be done following guidance provided by the TOE.

** At least 5 test enrolment transactions shall be performed by the test subject to make sure that the test suject can enrol correctly.

** In case of repeated failures during these test enrolment, the test subject shall use a different body part (this could mean to use a different finger of the test subject in case of fingerprint verification) and start test enrolment transactions again.

** If the test subject cannot enrol any body parts during test enrolment, the test subject shall be exempt from further testing. 

==== Artefact production 
The production of artefacts for each toolbox shall be performed as follows:

* The evaluator shall produce all artefacts defined in the toolbox.

* The evaluator shall follow instructions in the toolbox to produce artefacts, especially the evaluator shall use tools or materials (e.g. camera, display or printer) that meet requirements in toolbox.

* The evaluator shall produce three artefacts from each test subject.

* The evaluator shall document any necessary information so that the evaluator can re-produce artefacts used for the test.

* Each produced artefact shall be identified by a unique identifier. This identifier shall be be attached to the artefact at all times (as far as this is possible without destroying the artefact).

==== Presentation of artefacts
The evaluator shall present artefacts to the TOE to perform presentation attacks.

* Each artefact shall be presented to the TOE 10 times

** If the TOE matches the artefact to the enrolled user, the attempt is considered a attack presentation match attempt. 

** If the TOE rejects the artefact, presentation attack fails.

=== Number of Subjects
The evaluator shall prepare three test subjects for the above test. A test subject is defined as one individual, and not different body parts from one person (i.e. three fingers from one person could not be considered to be three test subjects for the creation of artefacts).

=== Pass/Fail Criteria
The following pass criteria shall be applied if no other criteria are defined in the toolbox. 

A TOE passes the test if and only if it reliably defeats the use of *all artefacts (i.e. 3 X 3 = 9 artefacts in total)* that have to be built according to the toolbox. This means that none of the artefacts must be able to reproducibly overcome the TOE. 

To reproducibly overcome the TOE by the use of a *certain artefact* in the outlined test scenario is defined as follows:

.Pass/Fail Criteria
[cols="1,1,3",options="header"]
|===

|Attempts
|Number of matches
|Outcome  

|10
|0
|TOE passes this artefact

|10
|1
|TOE passes this artefact

|10
|2
|Additional ten (10) attempts shall be made

|20
|2
|TOE passes this aretefact

|Up to 20
|3 or more
|TOE fails this aretefact

|===

The maximum number of attempts allowed with one artefact is twenty (20). If three (3) matches are made to the artefact, independent test fails (further attempts are not necessary even if 20 total attempts have not yet been made).

== Common guidance for penetration test
The evaluator can move to penetration test only if the TOE passes independent test. As described in <<SD>> Section 6, the evaluator shall select those artefacts that show higher attack presentation match rate during independent test or higher quality artefacts.

The same guidance in Section 5 applies to penetration testing except those in __italic__.

=== General test protocol
Presentation attack can be performed through the following three steps. 

==== Preparation
Before the actual test can start, the following pre-requisites need to be met:

* It has to be ensured that the test subject whose body part is used to produce the artefacts for testing is enrolled into the TOE correctly as follows.

** Enrolment shall be done following guidance provided by the TOE.

** At least 5 test enrolment transactions shall be performed by the test subject to make sure that the test suject can enrol correctly.

** In case of repeated failures during these test enrolment, the test subject shall use a different body part (this could mean to use a different finger of the test subject in case of fingerprint verification) and start test enrolment transactions again.

** If the test subject cannot enrol any body parts during test enrolment, the test subject shall be exempt from further testing. 

==== Artefact production 
The production of artefacts for each toolbox shall be performed as follows:

* __The evaluator should select artefacts in a toolbox that may produce attack presentation match at higher probability considering the result of independent test.__

* __The evaluator may refine the production process of artefacts, as explained in <<SD>> Section 6. Toolbox describes generalized process to produce artefacts refering reseach papers. These research papers may describe more detail information to produce better artefacts. Such information is valuable information if the TOE's PAD algorithm is the same as ones tested by reseachers. The evaluator shall take such infomration into consideration to improve artefacts if the evaluator can find the relevant research papers.__

* __The evaluator may produce arbitary number of artefacts from each test subject within allowed time period. As described in <<SD>>, both independent and penetration test shall be finished within one week.__

* The evaluator shall document any necessary information so that the evaluator can re-produce artefacts used for the test.

* Each produced artefact shall be identified by a unique identifier. This identifier shall be be attached to the artefact at all times (as far as this is possible without destroying the artefact).

==== Presentation of artefacts
The evaluator shall present artefacts to the TOE to perform presentation attacks.

* __Each artefact shall be presented to the TOE arbitary number of times within allowed time period. As described in <<SD>>, both independent and penetration test shall be finished within one week.__

** If the TOE matches the artefact to the enrolled user, the attempt is considered a attack presentation match attempt. 

** If the TOE rejects the artefact, presentation attack fails.

=== Number of Subjects
__If the evaluator can create artefacts that produce attack presentation match during independent testing, the evalautor should select test subjects from which the artefacts created and increase the number of attemps. The evaluator may change the test subject for penetration test as described in <<SD>> Section 6.__

=== Pass/Fail Criteria
__As described in <<SD>>, both independent and penetration test shall be finished within one week. The evaluator may select one or two artefacts and perform arbitary number of attempts within this time period. If the evaluator can create artefacts that meet the criteira defined in <<SD>> Section 9.3, the TOE fails AVA_VAN.1 evaluation.__

== Literature

- [#BIOPP-Module]#[BIOPP-Module]# collaborative PP-Module for Biometric enrolment and verification - for unlocking the device -, December 5, 2019, Version 0.91
- [#SD]#[SD]# Supporting Document Mandatory Technical Document: Evaluation Activities for collaborative PP-Module for Biometric enrolment and verification - for unlocking the device -, December 05, 2019, Version 0.5

