= Toolbox Overview 
:showtitle:
:toc:
:sectnums:
:imagesdir: images
:icons: font
:revnumber: 0.5
:revdate: 2019-12-06

== Introduction
The TOE may be vulnerable to presentation attacks where attackers attempt to subvert the biometric enrolment or verification by presenting the Presentation Attack Instrument(PAI)s that are natural biometric characteristics such as dead eye or artefacts holding copied or faked characteristics. Using national biometric characteristics is out of scope of <<BIOPP-Module>> evaluation and the evaluator shall create only artefacts to evaluate the TOE. 

Toolbox defines the common artefacts for each biometric modality based on publicly available information (e.g. research papers), experiences and knowledge shared among the BIO-iTC members. The evaluator needs to read <<SD>> Section 6 first to use a toolbox because it explains how the evaluator shall use it during ATE_IND.1 and AVA_VAN.1 evaluation for PAD in detail.

This overview is originally developped for evaluation activities for FIA_MBV_EXT.3, however, the evaluator can apply the same principle to evaluation activities for FIA_MBE_EXT.3.

== Biometric modality supported

Currently toolbox is developed for the following biometric modalities:

* Eye
* Face
** 2D Image
** 3D Image
* Fingerprint
* Vein

== Purpose of this toolbox overview

This toolbox overview describes anything in common for all toolboxes, rather than repeating the same information in each toolbox. The evalator shall refer both the toolbox overview and relevant toolbox to perform ATE_IND.1 and AVA_VAN.1 evaluation. If there is conflict between the toolbox overview and each toolbox, the toolbox takes precedence over the toolbox overvew.

== Structure of toolbox

Each toolbox share the same structure and includes following sections.

* _modality name_ Toolbox overview
This section provides specific information only applicable to relevant biometric modality.

* _modality name_ Toolbox Inventory
This section categorizes tools and materials that the evaluator shall use to capture a image of biometric characteristics and produce artefacts.

* Mobile Toolbox for _modality name_ Verification List
This section summarizes all test items that the evaluator shall peform during the ATE_IND.1 evaluation. As explained in <<SD>> Section 6, the evaluator shall select specific test items for AVA_VAN.1 evaluation based on the result of ATE_IND.1 evaluation. 

* References
This section lists all publicly available information referred to create a toolbox.

* Test items
Each test item includes the following sub-sections. This toolbox overview provide a general test protocol in common for all toolboxes and these test items describe more detailed information to enable repeatable testing.

|===

|Sub-section name | Description

|Number
|Identification number of test

|Attack type
|Category of attack

|Overview
|General overview of test

|Input
|Required input to produce artefacts

|Tools
|Required tools to capture a image of biometric characteristics and produce artefacts

|Recipe
|Procedure to create artefacts

|Variations
|Variations of tests that the evaluator should consider AVA_VAN.1 evaluation

|Prerequisite
|Any conditions that should meet to perform each test

|Presentation
|Detail instraction to present artefact to the TOE

|Attack Potential
|Attack potential rating that the evaluator shall use for AVA_VAN.1 evaluation

|Pass Criteria
|If this Pass criteria is defined in test items, evaluator shall follow it. Otherwise, the evaluator shall follow criteria defined in this toolbox overview for ATE_IND.1 and one defined in <<SD>> Section 9.3 for AVA_VAN.1  

|===

== Common guidance for ATE_IND.1 evalaution
As explained in <<BIOPP-Module>>, the TOE is the whole biometric system, including Comparison, Decision and Presentation Attack Detection Subsystems. This means that - in order to successfully overcome the TOE by the use of artefacts - a genuine person (test subject) has to be enrolled into the TOE, artefacts have to be created referring the toolbox for the corresponding biometric modality and artefacts have to produce a match (i.e. a successful biometric verification).

The following guidance is common in all toolboxes. More specific guidance to specific biometric modality is provided in each toolbox. 

=== General test protocol
Presentation attack can be performed through the following three steps. 

==== Preparation
Before the actual test can start, the following pre-requisites need to be met:

* It has to be ensured that the test subject whose body part is used to produce the artefacts for testing is enrolled into the TOE correctly as follows.

** Enrolment shall be done following guidance provided by the TOE.

** At least 5 test enrolment transactions shall be performed by the test subject to make sure that the test suject can enrol correctly.

** In case of repeated failures during these test enrolment, the test subject shall use a different body part (this could mean to use a different finger of the test subject in case of fingerprint verification) and start test enrolment transactions again.

** If the test subject cannot enrol any body parts during test enrolment, the test subject shall be exempt from further testing. 

=== Artefact production 
The production of artefacts for each toolbox shall be performed as follows:

* The evaluator shall produce all artefacts defined in the toolbox.
* The evaluator shall follow instructions in the toolbox to produce artefacts, especially the evaluator shall use tools or materials (e.g. camera, display or printer) that meet requirements in toolbox.
* The evaluator shall produce three artefacts from each test subject if the toolbox doesn't define any specific numbers. If the toolbox defines the numbers, the evaluator shall produce required amount of artefacts.
* The evaluator shall document any necessary information so that the evaluato can re-produce artefacts used for the test.
* Each produced artefact shall be identified by a unique identifier. This identifier shall be be attached to the artefact at all times (as far as this is possible without destroying the artefact).

=== Presentation of artefacts
The evaluator shall present artefacts to the TOE to perform presentation attacks.

* The user is enrolled to the TOE
* Artefacts are created according to the attack instructions
* The artefact shall be applied to the TOE 10 times
** If the TOE matches the artefact to the enrolled user, the attempt is considered a failed attempt. 
** If the TOE rejects the artefact, this is considered being a passed attempt.

=== Number of Subjects
For the purposes of the PAD testing, the evaluator shall prepare three test subjects for the creation of artefacts. A test subject is defined as one individual, and not different body parts from one person (i.e. three fingers from one person could not be considered to be three test subjects for the creation of artefacts).

=== Pass/Fail Criteria
The following pass criteria shall be applied if no other criteria are defined in the individual modality toolbox documents. 

A TOE passes the test if and only if it reliably defeats the use of *all artefacts* that have to be built according to the toolbox. This means that none of the artefacts must be able to reproducibly overcome the TOE. 

To reproducibly overcome the TOE by the use of a *certain artefact* in the outlined test scenario is defined as follows:

.Pass/Fail Criteria
[cols="1,1,3",options="header"]
|===

|Attempts
|PAI Matches
|Outcome  

|10
|0
|TOE passes this PAI  

|10
|1
|TOE passes this PAI  

|10
|2
|Additional ten (10) attempts are allowed with this PAI  

|20
|2
|TOE passes this PAI

|Up to 20
|3 or more
|TOE fails this PAI

|===

The maximum number of attempts allowed with a PAI is twenty (20). If three (3) matches are made to the PAI, the test fails (further attempts are not necessary even if 20 total attempts have not yet been made).

== Literature

- [#BIOPP-Module]#[BIOPP-Module]# collaborative PP-Module for Biometric enrolment and verification - for unlocking the device -, December 5, 2019, Version 0.91
- [#SD]#[SD]# Supporting Document Mandatory Technical Document: Evaluation Activities for collaborative PP-Module for Biometric enrolment and verification - for unlocking the device -, December 05, 2019, Version 0.5

