= 2D face image toolbox inventory

This document specify requirements for tools that are used to create 2D face image artefacts. There are two types of tools, Type 1 and Type 2. The evaluator shall create normal quality of face artefacts using Type 1 tools and high quality face artefacts with Type 2 tools. Requirement for each tool is specified in the following table.

The evaluator may use any tools to create 2D face artefacts as long as they meet requirements specified below. The evalautor may use any available services (e.g. rental service) to prepare any tools in cost effective way.

The evaluator may need to use other tools that are not specified here. For example, the evaluator may connect the camera to the TV directly to display the face image on the 4K screen. But she can also prepare the PC and viewer software and import face image file from the camera to the PC and display it on the 4K PC screen. In such cases, the evaluator may use any tools, however, the evaluator shall visually check the final image on the screen and if the evalautor see any problem (e.g. choppy video playback because of weak cpu power), the evaluator shall replace them with right ones.  

.Tool requirement
[cols="4*"]
|===

| ID  | Category            | Type 1                     | Type 2    

| T.1 
| Camera    
a|Rear-facing camera of a movile device  

* The evaluator shall not use the same movile device on which the TOE is installed.
* New movile device shall be purchasable at the date of testing.
* Camera's resolution should be the same level or higher than the TOE's sensor used for face biometric verification.
a|dSLR camera

* New dSLR shall be purchasable at the date of testing and the camera was released within 1 year from the date of testing.
* Camera's resolution shall be at least 3 times higher than the TOE's sensor used for face biometric verification.

| T.2 
| Printer             
a|Home SoHo Inkjet printer 

* New printer shall be purchasable at the date of testing.
* Test user's face shall be printed on a paper in full scale.
a|Net print service

* Test user's face shall be printed on a paper in full scale.
* The evaluator shall refer publicly available information to select the best one (e.g. quality comparison report for netprint services). 
* The evaluator shall follow recommendations from net print service (e.g. recommended image file size) to get the highest quality of photo print. 

| T.3 
| Print paper            
a|Matte paper 

* Paper shall be wide enough to include a test user's face in full scale.

a|Paper recommend by net print service selected

* Paper shall be wide enough to include a test user's face in full scale.
* The evaluator shall select the best paper type to print the best quality of face images.

| T.4 
| Screen              
a|Mobile device screen

* The evaluator shall use the same mobile device used for capturing test user's face.
* Test user's face shall be displayed or replayed on the screen in full scale.
a|High resolution screen

* The evaluator shall use the highest resolution screen that was released within 1 year from the date of testing.
* Test user's face shall be displayed or replayed on the screen in full scale.

|===
