== Number
2D Face 1-2

=== Attack type
Digital photo attack, Normal quality

== Overview
The evaluator caputures and displays target user's face on the mobile screen and present it to the TOE.

== Input
Target user's face

== Tools
Type 1 tools in <<2DFaceInventory>> except T.2 (Printer) and T.3 (Print paper)

== Recipe
The evaluator shall capture a face image and display it on a mobile screen. 

The evaluator shall refer publicly available information to change default setting of the camera (e.g. FPS) and mobile device to create clearer face artefacts.

The evaulator shall take at least three photos and select the bese one to create each face artefact.

== Variations
The evaluator shall consider to change the following factors for penetration testing.

* Configuration of tool
+
The evaluator can change, for example, FPS (Frames Per Second) or ISO number of camera to change quality of face images. Such change may affect the texture of artefacts that may lead to false acceptance. 

* Presentation method
+ 
As described in <<BIOSD>>, the evaluator can change the distance between the artefact and the TOE. 

== Prerequisite
The evaluator shall enrol test users first as described in <<2DFaceOverview>>. If the ST covers the multiple configurations for face unlock, the same test should be done for all configurations.

== Presentation
The evaluator shall present a mobile screen by hand as described in <<2DFaceOverview>>.

== Attack Potential
The attack potential that is required to build this artefact is summarized in the following table. See <<SD>> Section 9 for more information about how to caluculate the attack potential. 

[cols=",,",options="header",]
.Attack Potential
|=======================
|Factor |Value |
| |Identification |Exploitation

|*Elapsed Time*
|<= one week (1) 
|<= one day (0)

|*Expertise*
|<= Layman (0) 
|<= Layman (0)
 
|*Knowledge of TOE*    
|Public (0)   
|N/A

a|
*Window of Opportunity*

*(Access to TOE)* 
|Easy (0)
|Moderate (4)

a|
*Window of Opportunity*

*(Access to Biometric Characteristics)* 
|N/A
|Immediate (0)

|*Equipment*
|Standard (0)   
|Standard (0) 

3+^.^|Total Attack Potential = 5 < Basic Attack Potential

|=======================

== Pass Criteria
There is no additional criteira other than defined in <<BIOSD>> and <<ToolOverview>>.
