== Number
2D Face 2-1

== Attack type
Printed photo attack, High quality

== Overview
The evaluator caputures and prints target user's face on the paper and present it to the TOE.

== Input
Target user's face

== Tools
Type 2 tools in <<2DFaceInventory>> except T.4 (Screen)

== Recipe
The evaluator shall capture a face image and print it on a paper. 

The evaluator shall refer publicly available information to change default setting of the camera (e.g. ISO value) to create clearer face artefacts.

The evaulator shall take at least three photos and select the best one to create each face artefact.

== Variations
The evaluator shall consider to change the following factors for penetration testing.

* Configuration of tool
+
The evaluator can change, for example, shutter speed of camera to change quality of face images. Such change may affect the texture of artefacts that may lead to false acceptance. 

* Presentation method
+ 
As described in <<BIOSD>>, the evaluator can change the distance between the artefact and the TOE. In addtion to that, the evaluator can deliberately warps a printed photo, trying to simulate facial motion (Warped photo attack). The evaluator can also cut off the eye regions of a printed photo, hide behind and exhibit blinking through the holes (Cut photo attack).  

== Prerequisite
The evaluator shall enrol test users first as described in <<2DFaceOverview>>. If the ST covers the multiple configurations for face unlock, the same test should be done for all configurations.

== Presentation
The evaluator shall present a printed photo by hand as described in <<2DFaceOverview>>.

== Attack Potential
The attack potential that is required to build this artefact is summarized in the following table. See <<SD>> Section 9 for more information about how to caluculate the attack potential. 

[cols=",,",options="header",]
.Attack Potential
|=======================
|Factor |Value |
| |Identification |Exploitation

|*Elapsed Time*
|<= one week (1) 
|<= one day (0)

|*Expertise*
|<= Layman (0) 
|<= Layman (0)
 
|*Knowledge of TOE*    
|Public (0)   
|N/A

a|
*Window of Opportunity*

*(Access to TOE)* 
|Easy (0)
|Moderate (4)

a|
*Window of Opportunity*

*(Access to Biometric Characteristics)* 
|N/A
|Immediate (0)

|*Equipment*
|Standard (0)   
|Standard (0) 

3+^.^|Total Attack Potential = 5 < Basic Attack Potential

|=======================

== Pass Criteria
There is no additional criteira other than defined in <<BIOSD>> and <<ToolOverview>>.
