== Number
2D Face 1-1

== Attack type
Printed photo attack, Normal quality

== Overview
The evaluator prints target user's face on the paper and present it to the TOE

== Input
Target user's face

== Tools
Type 1 tools in <<2DFaceInventory>>

== Recipe
The evaluator shall capture a face image and print it on a paper. 

The evaluator shall refer publicly available information to change default setting of the camera (e.g. FPS) and printer (e.g. resolution) to create clearer face artefacts.

The evaulator shall take at least three photos and select the bese one to create each face artefact.

== Variations
The evaluator shall consider to change the following factors for penetration testing.

* Configuration of tool
+
The evaluator can change, for example, FPS (Frames Per Second) or ISO number of camera to change quality of face images. Such change may affect the texture of artefacts that may lead to false acceptance. 

* Presentation method
+ 
As described in <<BIOSD>>, the evaluator can change the distance between the artefact and the TOE. In addtion to that, the evaluator can deliberately warps a printed photo, trying to simulate facial motion (Warped photo attack). The evaluator can also cut off the eye regions of a printed photo, hide behind and exhibit blinking through the holes (Cut photo attack).  

== Prerequisite
The evaluator shall enrol test users first as described in <<2DFaceOverview>>. If the ST covers the multiple configurations for face unlock, the same test should be done for all configurations.

== Presentation
The evaluator shall present a printed photo by hand as described in <<2DFaceOverview>>.

== Attack Potential
The attack potential that is required to build this artefact is summarized in the following table. 

.Attack Potential
[options="header,footer"]
|=======================
|Factor|Value
2+|*Elapsed Time*
|<= one week  |1     
2+|*Expertise*    
|Layman   |0     
2+|*Knowledge of TOE*    
|Public   |0 
2+|*Window of Opportunity*   
|Unnecessary   |0
2+|*Equipment*
|Standard   |0 
|=======================

== Pass Criteria
There is no additional criteira other than defined in <<BIOSD>> and <<ToolOverview>>.

