== Number
2D Face 1-3

=== Attack type
Replay video attack, Normal quality

== Overview
The evaluator records and replays target user's face on a mobile device screen and present it to the TOE.

== Input
Target user's face

== Tools
Type 1 tools in <<2DFaceInventory>> except T.2 (Printer) and T.3 (Print paper)

== Recipe
The evaluator shall record a face image and replay it on a mobile device screen. 

The evaluator shall refer publicly available information to change default setting of the camera (e.g. FPS (Frames Per Second)) to create clearer face artefacts.

The evaluator shall take at least three videos and select the best one to create each face artefact.

== Variations
=== Variation 1 (2D Face 2-3)
This variant uses Type 2 tools in <<2DFaceInventory>> except T.2 (Printer) and T.3 (Print paper) to conduct high quality replay video attacks.

== Prerequisite
The evaluator shall enroll test users first as described in <<2DFaceOverview>>. If the ST covers the multiple configurations for face unlock, the same test should be done for all configurations.

== Presentation
The evaluator shall present a mobile device screen by tripod for 10 seconds as described in <<2DFaceOverview>>.

== Penetration Testing and Attack Potential Rating Suggestions
=== Penetration Testing Suggestion
The evaluator shall consider changing the following factors for penetration testing.

* Configuration of tool
+
The evaluator can change, for example, color effect of camera to change quality of face images. Such change may affect the texture of artefacts that may lead to false acceptance. 

* Presentation method
+ 
As described in <<BIOSD>>, the evaluator can change the distance between the artefact and the TOE. 

=== Attack Potential Rating Suggestion
The attack potential that is required to build this artefact is summarized in the following table. See <<BIOSD>> Section 9 for more information about how to calculate the attack potential. 

[cols=",,",options="header",]
.Attack Potential
|=======================
|Factor |Value |
| |Identification |Exploitation

|*Elapsed Time*
|<= one week (1) 
|<= one day (0)

|*Expertise*
|<= Layman (0) 
|<= Layman (0)
 
|*Knowledge of TOE*    
|Public (0)   
|N/A

a|
*Window of Opportunity*

*(Access to TOE)* 
|Easy (0)
|Moderate (4)

a|
*Window of Opportunity*

*(Access to Biometric Characteristics)* 
|N/A
|Immediate (0)

|*Equipment*
|Standard (0)   
|Standard (0) 

3+^.^|Total Attack Potential = 5 < Basic Attack Potential

|=======================

== Pass Criteria
There are no additional criteria other than defined in <<BIOSD>> and <<ToolOverview>>.
