== Number
2D Face 5-2

== Attack type
tbd

==== Total Number of Species
This attack has *1* species to be tested.

== Overview
In this attack, target user needs to take a 3D scan to create the PAI which is much more similar as the genuine face. However, this attack does require user cooperation to create the PAI.

_*See [Liu et al., 2016] or [Bhattacharjee & Marcel, 2017] for more info Table will be created after fixing No.1-4.*_

== Input
tbd

== Tools
tbd

== Recipe
tbd

== Variations
tbd

== Prerequisite
tbd

== Presentation
tbd

== PAD technique
tbd

== Reference
tbd

== Attack Potential
The attack potential that is required to build this artefact is summarized in the following table. 

.Attack Potential
[options="header,footer"]
|=======================
|Factor|Value
2+|*Elapsed Time*
|<= one week  |?     
2+|*Expertise*    
|Layman   |?     
2+|*Knowledge of TOE*    
|Public   |? 
2+|*Window of Opportunity*   
|Unnecessary   |?
2+|*Equipment*
|Standard   |? 
|=======================

== Pass Criteria
tbd